name: Angular App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
       node-version: 18.15.0
       cache: 'npm'
       
    - name: Installing dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Unit Test
      run: npm test

    - name: Build App
      run: npm run build
